apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: packit-cli
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: packit-cli
    app.kubernetes.io/part-of: packit-fork
  name: packit-cli
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: packit-cli
status:
  loadBalancer: {}
